# Generated by Django 6.0 on 2026-05-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_fix_platform_payment_for_securing_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='featured_payment_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='featured_payment_requested_plan',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='featured_plan',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='featured_until',
            field=models.DateTimeField(blank=True, help_text='Listing appears first in search and on the homepage until this time.', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Booking request — awaiting owner'), ('accepted', 'Accepted — arrange payment with host'), ('secured', 'Confirmed — payment captured'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='payment_preference',
            field=models.CharField(choices=[('platform', 'They pay on Qasha'), ('direct', 'They pay me (the owner)')], default='platform', max_length=20),
        ),
    ]
