# Generated by Django 6.0 on 2026-05-29 12:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0010_amenity_custom_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='amenity',
            index=models.Index(fields=['is_custom', 'name'], name='rentals_amenity_custom'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['property', 'status'], name='rentals_booking_host'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['guest', 'status'], name='rentals_booking_guest'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['recipient', 'is_read'], name='rentals_msg_unread'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['recipient', '-created_at'], name='rentals_msg_inbox'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', '-created_at'], name='rentals_msg_sent'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_published', 'is_available', 'is_occupied', '-created_at'], name='rentals_prop_browse_new'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_published', 'is_available', 'is_occupied', 'city'], name='rentals_prop_browse_city'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['-featured_until'], name='rentals_prop_featured'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city'], name='rentals_prop_city'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['suburb'], name='rentals_prop_suburb'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['host', '-created_at'], name='rentals_prop_host_new'),
        ),
        migrations.AddIndex(
            model_name='propertyamenity',
            index=models.Index(fields=['amenity'], name='rentals_pamenity_amenity'),
        ),
        migrations.AddIndex(
            model_name='propertyimage',
            index=models.Index(fields=['property', '-is_primary', 'created_at'], name='rentals_pimg_display'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['user'], name='rentals_wishlist_user'),
        ),
    ]
