# Generated by Django 6.0 on 2026-02-12 20:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata_code', models.CharField(help_text='3-letter IATA code (e.g. JNB, JFK, LHR).', max_length=3, unique=True)),
                ('name', models.CharField(help_text='Airport name.', max_length=255)),
                ('city', models.CharField(help_text='City or metro area.', max_length=100)),
                ('country', models.CharField(help_text='Country name.', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Use this to disable closed / inactive airports.')),
            ],
            options={
                'ordering': ['city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='Public booking reference shown to customer (e.g. HAM12345).', max_length=20, unique=True)),
                ('currency', models.CharField(default='ZAR', max_length=3)),
                ('total_base_fare', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_taxes', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_extras', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('contact_email', models.EmailField(help_text='Primary email for sending tickets.', max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(blank=True, help_text='Source of booking (web, agent, etc.).', max_length=50)),
                ('internal_notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlightSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_name', models.CharField(max_length=100)),
                ('flight_number', models.CharField(max_length=20)),
                ('origin_airport_code', models.CharField(max_length=10)),
                ('origin_airport_name', models.CharField(blank=True, max_length=100)),
                ('destination_airport_code', models.CharField(max_length=10)),
                ('destination_airport_name', models.CharField(blank=True, max_length=100)),
                ('departure_datetime', models.DateTimeField()),
                ('arrival_datetime', models.DateTimeField()),
                ('cabin_class', models.CharField(default='ECONOMY', help_text='e.g. economy, premium, business', max_length=20)),
                ('hand_baggage_kg', models.DecimalField(blank=True, decimal_places=1, help_text='Hand baggage allowance in kg.', max_digits=5, null=True)),
                ('checked_baggage_kg', models.DecimalField(blank=True, decimal_places=1, help_text='Checked baggage allowance in kg.', max_digits=5, null=True)),
                ('direction', models.CharField(blank=True, help_text='Optional: OUTBOUND or RETURN for display purposes.', max_length=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_segments', to='booking.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Payer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('billing_address_line1', models.CharField(blank=True, max_length=100)),
                ('billing_address_line2', models.CharField(blank=True, max_length=100)),
                ('billing_city', models.CharField(blank=True, max_length=50)),
                ('billing_postcode', models.CharField(blank=True, max_length=20)),
                ('billing_country', models.CharField(blank=True, max_length=50)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payer', to='booking.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='ZAR', max_length=3)),
                ('method', models.CharField(choices=[('CARD', 'Card'), ('EFT', 'EFT / Bank transfer'), ('WALLET', 'Mobile wallet'), ('OTHER', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('provider_reference', models.CharField(blank=True, help_text='Payment gateway reference / transaction id.', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('raw_response', models.JSONField(blank=True, help_text='Optional: store gateway response.', null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='booking.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('document_number', models.CharField(blank=True, help_text='ID / passport number', max_length=50)),
                ('nationality', models.CharField(blank=True, max_length=50)),
                ('is_primary_contact', models.BooleanField(default=False)),
                ('special_requests', models.TextField(blank=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travelers', to='booking.booking')),
            ],
        ),
        migrations.CreateModel(
            name='BookingExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_type', models.CharField(choices=[('WHATSAPP_TICKET', 'Get ticket via WhatsApp'), ('SMS_TICKET', 'Get ticket via SMS'), ('REFUND_INSURANCE', 'Full refund insurance (illness/death/hospitalisation)'), ('DATE_CHANGE_OPTION', 'One date change without airline penalty')], max_length=50)),
                ('description', models.CharField(help_text='User-facing description at time of booking (snapshot).', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='ZAR', max_length=3)),
                ('applies_to_all_travelers', models.BooleanField(default=True, help_text='If false, use `applies_to_travelers` to specify travelers.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='booking.booking')),
                ('applies_to_travelers', models.ManyToManyField(blank=True, related_name='extras', to='booking.traveler')),
            ],
        ),
    ]
