# Generated by Django 6.0 on 2026-05-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_account_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='host_verification_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='host_verification_requested_tier',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='host_verification_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='host_verification_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='host_verification_tier',
            field=models.CharField(blank=True, choices=[('', 'None'), ('landlord', 'Landlord'), ('agency', 'Agency')], default='', max_length=20),
        ),
    ]
